### ISSUE TITLE
Thanks again for this great theme. code blocks are a little awkard on desktop.

### ISSUE THREAD

**Issue by Jieiku** [welpo/tabi#114]
You have innovated a lot of good things with this theme, very good attention to detail. Many were used in abridge or inspiration for a similar feature.

One thing I noticed while browsing the demo site is the code blocks don't have a very good way to scroll horizontally, maybe not an issue on mobile since you can use your finger to pan the frame, but its awkward on desktop.

In abridge I have a horizontal scroll bar for code blocks, but I am also considering implementing a button to expand the view to fullscreen, I found one such example here : https://dev.to/prorishi/your-static-site-to-a-pwa-24dl (notice the button in the top right corner of code blocks)

I am thinking of implementing something similar, especially if I can accomplish it without js.

Also somebody recently suggested styling the scrollbars in chrome, with a property I had not even heard of (mostly because I use Firefox) here was the issue: https://github.com/Jieiku/abridge/issues/136 (implementing the feature was not too difficult)

**Comment by welpo** [comment]
Hey Jake!

Thanks for your kind comments. You already know Abridge has been a source of inspiration for this theme as well. I'm glad we can both help each other :)

You're right about the horizontal scrolling not being too obvious. It should be possible with Shift + Scroll, though. It's standard OS behaviour in Windows and macOS, but not many know about this.

I hid the scrollbars because I don't like them for codeblocks, but I think this is something that should follow user preference, so I'll add them back (and hide them for myself through the OS settings).

Regarding the button to expand codeblocks, I think it'll be hard without JavaScript, unless you use a shortcode to build the codeblock. That way you can create a switcher for it and change its display through CSS when activated (I use this toggle function for the multilingual quote, image toggler and the spoiler shortcodes).

Thanks for sharing the Chrome styling info! I will definitely look into it!

**Comment by welpo** [comment]
Implemented both suggestions (dark/light scrollbars & unhiding them) on commits above.

Like you, I opted not to modify the logic of the JS theme switcher to have the scrollbars instantly react to the theme changes (https://stackoverflow.com/a/66097469); it feels kind of dirty forcing a reflow and adding JS complexity (and bytes) for this minor benefit.
