### ISSUE TITLE
Support Webmentions for comments

### ISSUE THREAD

**Issue by azzamsa** [welpo/tabi#237]
# Feature Request

## Summary

Hi, Óscar  👋.

Would you like to support Webmentions as a commenting system alternative?

## Motivation

I love using something that will last long, and I can keep it forever. GitHub doesn't fall into this criteria, so not Utterances and Disqus.

I love Isso, but it requires me to self-host it somewhere.

Webmentions, on the other hand, fetch the comments and likes and store them in JSON format in our local storage alongside our website codebase. We can keep it forever, with no additional self-hosting cost.

However, it only keeps the comments locally; the profile picture is still fetched from their respective platform.

## Detailed Description

- https://indieweb.org/Webmention
- https://webmention.io/
- [An In-Depth Tutorial of Webmentions + Eleventy](https://sia.codes/posts/webmentions-eleventy-in-depth/)

![image](https://github.com/welpo/tabi/assets/17734314/8a26a38a-b683-436a-8458-e43f5a3dff95)

- https://web.archive.org/web/20231231054007/https://www.zachleat.com/web/jamstack-future/

**Comment by welpo** [comment]
Hi!

I was not familiar with Webmentions. This looks like a complex setup; you might need the [`load_data` ](https://www.getzola.org/documentation/templates/overview/#load-data) function be useful here.

I'm not interested in adding more commenting systems to tabi myself. However, I would take a PR for this, provided it doesn't add any build dependencies (that is, that users can simply set up some variables in `config.toml` and have it work).

Happy to provide assistance where necessary otherwise.
