### ISSUE TITLE
theme switcher on demo, takes 2 click initially.

### ISSUE THREAD

**Issue by Jieiku** [welpo/tabi#94]
My system / browser preference is dark.

If I clear my browser cache or open a private browsing session, then visit: https://welpo.github.io/tabi/

The page initially loads with the dark theme.

I then click the theme switcher... nothing happens.

I click the theme switcher again... this time it changes.

Every click thereafter changes as expected.

This was in firefox.

I then set my browser preference to light mode, and opened the site in a fresh private browser.

Under this mode the theme switcher works correctly.

So seems the theme switcher only requires the extra click for people that have a browser or OS with dark mode preference.

**Comment by welpo** [comment]
Thanks for reporting this.

The issue was due to the `currentTheme` variable not being initialized when the system preference is used to set the theme at the start of the page load. Thus, when the theme switcher was first clicked, it didn't work as expected because `currentTheme` was `null` instead of being either 'dark' or 'light'.

I've corrected this by ensuring the `currentTheme` variable is properly initialized based on the system preference if there's no saved theme in localStorage. The theme switcher should now work correctly on the first click, regardless of your system's color scheme preference.
